---
title: "xRank"
output:
  html_document: default
  pdf_document: default
permalink: rank/ 
resource_files: '.'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prep, echo=FALSE, message=FALSE, warning=FALSE}
library(reactable)
library(htmltools)
library(tibble)
library(forcats)
library(tidyverse)
library(sparkline)
library(dataui)

df1 <- readxl::read_excel("Export_TDL_NED_2122.xlsx", 
                   sheet = "Wedstrijden") %>%
  group_by(HomeName) %>% mutate(Team = HomeName,
                                   xG_diff = Home_xG - Away_xG) %>%
  ungroup() %>%
  select(date,Team, xG_diff)

df2 <- readxl::read_excel("Export_TDL_NED_2122.xlsx", 
                   sheet = "Wedstrijden") %>%
  group_by(AwayName) %>% mutate(Team = AwayName,
                                   xG_diff = Away_xG - Home_xG) %>%
  ungroup() %>%
  select(date,Team, xG_diff)


df <- 
  rbind(df1,df2) %>% 
  arrange(Team,as.Date(date,format="%d-%m-%Y")) %>% 
  group_by(Team) %>% 
  summarise(form = list(zoo::rollmean(xG_diff,5)),
                                                  xG = list(xG_diff),
            date=list(date))


df3 <- rbind(df1,df2) %>% arrange(Team,as.Date(date,format="%d-%m-%Y")) %>%
  
  group_by(Team) %>%
  slice_tail(n = 8) %>%
    summarise(form = list((xG_diff)),
              date=list(date))
```

```{r table, echo=FALSE, message=FALSE, warning=FALSE}
orange_pal <- function(x){
  rgb(colorRamp(c("green","white", "red"))(x), maxColorValue = 255)}

rating_cols <- c("spi", "global_o", "global_d")
group_cols <- c("group_1", "group_2", "group_3")
knockout_cols <- c("make_round_of_16", "make_quarters", "make_semis", "make_final", "win_league")
#forecasts <- forecasts[, c("team", "points", "group", rating_cols, group_cols, knockout_cols)]

rating_column <- function(maxWidth = 55, ...) {
  colDef(maxWidth = maxWidth, align = "center", class = "cell number", ...)
}

group_column <- function(class = NULL, ...) {
  colDef(cell = format_pct, maxWidth = 70, align = "center", class = paste("cell number", class), ...)
}

knockout_column <- function(maxWidth = 70, class = NULL, ...) {
  colDef(
    cell = format_pct,
    maxWidth = maxWidth,
    class = paste("cell number", class),
    style = function(value) {
      # Lighter color for <1%
      if (value < 0.01) {
        list(color = "#aaa")
      } else {
        list(color = "#111", background = knockout_pct_color(value))
      }
    },
    ...
  )
}

format_pct <- function(value) {
  if (value == 0) "  \u2013 "    # en dash for 0%
  else if (value == 1) "\u2713"  # checkmark for 100%
  else if (value < 0.01) " <1%"
  else if (value > 0.99) ">99%"
  else formatC(paste0(round(value * 100), "%"), width = 4)
}

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

with_tooltip <- function(value, tooltip) {
  tags$abbr(style = "text-decoration: underline; text-decoration-style: dotted; cursor: help",
            title = tooltip, value)
}

off_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1.3)
def_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 0.6)
knockout_pct_color <- make_color_pal(c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab"), bias = 2)

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}
good_color <- make_color_pal(c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab"), bias = 2)

#xRank <- xRank[,-2]
real_cols <- c("Rank","Logo","Team","P", "W", "D","L","GF","GA","GD","Pts")
expected_cols <- c("xGF", "xGA", "xGD","xPts","xRank", "Form")
group_column <- function(class = NULL, ...) {
  colDef(cell = format_pct, maxWidth = 70, align = "center", class = paste("cell number", class), ...)
}

xRank <- readxl::read_excel("Export_TDL_NED_2122.xlsx", 
                  sheet = "Stand")# %>% 
#  mutate(Form = NA)

xRank<- add_column(xRank, Logo = xRank$Team, .after = 1) 
xRank<- add_column(xRank, Form = NA, .after = 15) 
tbl <-   reactable(
      xRank,
      showSortable = TRUE,
       style = list(fontFamily = "Roboto, sans-serif", fontSize = "14px",class = "standings"),
      defaultColGroup = colGroup(headerClass = "group-header"),
      columnGroups = list(
        colGroup(name = "League Table", columns = real_cols),
        colGroup(name = "Expected", columns = expected_cols)),
      columns = list(
        
 Form = 
 colDef(show= TRUE, header = with_tooltip("Form", "xG difference last games"),
        #header = " ",
           minWidth = 58,
         align = "center",
                  cell = function(value, index) {
      data <- df3 %>% filter(Team == xRank$Team[index])
      
      
      
    sparkline(data$form[[1]],type = "bar", barColor = "green",  align = "center", 
              chartRangeMax = max(unlist(df$xG))) 
       
      
    }),
    

        Logo = colDef(minWidth = 40,
                      name = "",
                      cell = function(value) {
                        img_src <- knitr::image_uri(sprintf("Clubs/%s.png", value))
                        image <- img(src = img_src, height = "22px", alt = value)
                        tagList(
                          div(style = list(display = "inline-block", width = "40px"), image)
                        )
                      }),
        Team= colDef(minWidth = 140,
                     
                     align = "left",
        ),
  xPts = colDef(minWidth =65),
        xRank = colDef(minWidth =65,
                       align = "center",
                       cell = function(value,index){
                         if(xRank$xRank[index] < xRank$Rank[index]){
                           background <- "#61B861"
                         }else if(xRank$xRank[index] > xRank$Rank[index]){
                           background <- "#FC785F"
                         }else{
                           
                           background <- "#FDD297"
                         }
                         div(class = "spi-rating", style = list(background = background), value)
                       }),
        P = colDef(
          style = list(borderLeft = "2px solid rgba(0, 0, 0, 1)")
        ),
        xGF = colDef(
          style = list(borderLeft = "2px solid rgba(0, 0, 0, 1)")
        ),
        Rank = colDef(minWidth = 60,
                      align = "center",
                      
                      cell = function(value,index){
                        if(xRank$xRank[index] > xRank$Rank[index]){
                          background <- "#61B861"
                        }else if(xRank$xRank[index] < xRank$Rank[index]){
                          background <- "#FC785F"
                        }else{
                          
                          background <- "#FDD297"
                        }
                        div(class = "spi-rating", style = list(background = background), value)
                      })
      ),
      
      
      
      defaultColDef = colDef(
        class = "cell", 
        headerClass = "header",
        align = "center",
        minWidth = 50,
        headerStyle = list(background = "#f7f7f8")
      ),
   
      searchable = FALSE,
      defaultPageSize = 105,
      striped = TRUE,
      highlight = TRUE,
      # bordered = TRUE,
      compact = TRUE,
      theme = reactableTheme(
        borderColor = "#dfe2e5",
        stripedColor = "#f6f8fa",
        highlightColor = "#d7dce0",
        cellPadding = "6px 6px",
        
        
        searchInputStyle = list(width = "100%",height = "100%")
      )
    )

div(class = "standings",
  div(class = "title",
    h2("Expected Points Eredivisie 2021/2022"),
    "League table sorted on xPoints"
  ),
  tbl,
  "Based on simulating every shot in every match"
)
```

---

```{r ref.label="table", eval=FALSE,echo=FALSE}
```

```{r,echo=FALSE}
tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```

```{css,echo=FALSE}
.standings {
  font-family: Karla, "Roboto", Helvetica, Arial, sans-serif;
  font-size: 14px;
}

.title {
  margin: 18px 0;
  font-size: 16px;
}

.title h2 {
  font-size: 20px;
  font-weight: 600;
}

.standings-table {
  margin-bottom: 20px;
}

/* Align header text to the bottom */
.header,
.group-header {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}

.header {
  border-bottom-color: #555;
  font-size: 13px;
  font-weight: 400;
  text-transform: uppercase;
}

/* Highlight headers when sorting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #eee;
}

.border-left {
  border-left: 2px solid #555;
}

/* Use box-shadow to create row borders that appear behind vertical borders */
.cell {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
}

.group-last .cell {
  box-shadow: inset 0 -2px 0 #555;
}

.team {
  display: flex;
  align-items: baseline;
}

.record {
  margin-left: 5px;
  color: #999;
  font-size: 13px;
}

.team-name {
  font-size: 18px;
  font-weight: 700;
}

.flag {
  margin-right: 8px;
  height: 21px;
  border: 1px solid #f0f0f0;
}

.group {
  font-size: 19px;
}

.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 16px;
  line-height: 30px;
  white-space: pre;
}

.spi-rating {
  width: 20px;
  height: 20px;
  border: 1px solid rgba(0, 0, 0, 0.03);
  border-radius: 50%;
text-align: center;
  align-item: right;
   margin-left: 15px;
#  color: #000;
  font-size: 13px;
 # letter-spacing: -2px;
}
```


```{css echo=FALSE}
/* rmarkdown html documents */
.main-container {
  max-width: 1035px !important;
  font-family: 'Roboto', sans-serif;
  font-size: 12px;
    height: 20px;
}

h1.title {
  display: none;
}

/* pkgdown articles */
.contents {
  width: 1060px;
}

.page-header {
  display: none;
}
```
